export type Workout = {
  id: string;
  name: string;
  category: string;
  time: number;
  level: string;
  focus: string;
  moves: string[];
  xp: number;
};
export const workouts: Workout[] = [
  {
    id: "quick",
    name: "The 10-minute reset",
    category: "Quick workout",
    time: 10,
    level: "Beginner",
    focus: "Full body",
    moves: [
      "March in place · 45 sec",
      "Bodyweight squats · 10 reps",
      "Wall push-ups · 10 reps",
      "Standing knee drives · 12 reps",
      "Child’s pose · 45 sec",
    ],
    xp: 80,
  },
  {
    id: "strength",
    name: "Campus strength circuit",
    category: "Full body",
    time: 20,
    level: "All levels",
    focus: "Strength",
    moves: [
      "Squats · 12 reps",
      "Incline push-ups · 10 reps",
      "Glute bridges · 12 reps",
      "Dead bugs · 10 each side",
      "Rest · 45 sec",
    ],
    xp: 130,
  },
  {
    id: "mobility",
    name: "Desk-to-dynamic mobility",
    category: "Mobility",
    time: 12,
    level: "Beginner",
    focus: "Mobility",
    moves: [
      "Cat-cow · 8 breaths",
      "World’s greatest stretch · 4 each side",
      "Hip flexor stretch · 30 sec each",
      "Thoracic rotations · 8 each side",
      "Easy forward fold · 45 sec",
    ],
    xp: 90,
  },
  {
    id: "legs",
    name: "Leg day, no equipment",
    category: "Legs",
    time: 18,
    level: "Intermediate",
    focus: "Legs",
    moves: [
      "Reverse lunges · 10 each side",
      "Tempo squats · 12 reps",
      "Single-leg glute bridge · 8 each",
      "Calf raises · 15 reps",
      "Rest · 45 sec",
    ],
    xp: 120,
  },
];
export const exerciseLibrary = [
  {
    name: "Push-ups",
    category: "Chest",
    level: "Beginner",
    equipment: "None",
    target: "Chest · shoulders · arms",
    duration: "3 sets · 8–12 reps",
    mode: "Camera detection",
  },
  {
    name: "Knee push-ups",
    category: "Chest",
    level: "Beginner",
    equipment: "None",
    target: "Chest · shoulders · arms",
    duration: "3 sets · 8–12 reps",
    mode: "Camera detection",
  },
  {
    name: "Incline push-ups",
    category: "Chest",
    level: "Beginner",
    equipment: "Desk or wall",
    target: "Chest · shoulders · arms",
    duration: "3 sets · 8–12 reps",
    mode: "Camera detection",
  },
  {
    name: "Squats",
    category: "Legs",
    level: "Beginner",
    equipment: "None",
    target: "Quads · glutes",
    duration: "3 sets · 10–15 reps",
    mode: "Camera detection",
  },
  {
    name: "Lunges",
    category: "Legs",
    level: "Intermediate",
    equipment: "None",
    target: "Quads · glutes",
    duration: "3 sets · 8 each side",
    mode: "Camera detection",
  },
  {
    name: "Reverse lunges",
    category: "Legs",
    level: "Beginner",
    equipment: "None",
    target: "Quads · glutes",
    duration: "3 sets · 8 each side",
    mode: "Camera detection",
  },
  {
    name: "Glute bridges",
    category: "Legs",
    level: "Beginner",
    equipment: "Mat optional",
    target: "Glutes · hamstrings",
    duration: "3 sets · 12 reps",
    mode: "Camera detection",
  },
  {
    name: "Plank",
    category: "Core",
    level: "Beginner",
    equipment: "Mat optional",
    target: "Core stability · shoulder and hip alignment",
    duration: "3 sets · 30 sec",
    mode: "Camera detection",
  },
  ...["Crunches", "Mountain climbers"].map((name) => ({
    name,
    category: "Core",
    level: "Beginner",
    equipment: "Mat optional",
    target: "Core",
    duration: "3 sets · 30 sec",
    mode: "Manual tracking",
  })),
  ...["Shoulder press", "Arm raises", "Bicep curl"].map((name) => ({
    name,
    category: "Upper body",
    level: "Beginner",
    equipment: "Light weights optional",
    target: "Shoulders · arms",
    duration: "3 sets · 10–12 reps",
    mode: "Manual tracking",
  })),
  ...["Jumping jacks", "High knees", "Burpees"].map((name) => ({
    name,
    category: "Full body",
    level: "Intermediate",
    equipment: "None",
    target: "Full body",
    duration: "3 sets · 30 sec",
    mode: "Manual tracking",
  })),
  ...[
    "Cat-cow",
    "Child’s pose",
    "Tree pose",
    "Downward dog",
    "Warrior pose",
  ].map((name) => ({
    name,
    category: "Mobility / yoga",
    level: "All levels",
    equipment: "Mat optional",
    target: "Mobility · balance",
    duration: "1–3 min",
    mode: "Camera guidance",
  })),
];

const movementInstructions: Record<string, string[]> = {
  "march in place": ["Stand tall with feet under hips.", "March gently, lifting one knee at a time and swinging relaxed arms.", "Land softly and keep breathing steadily."],
  "rest": ["Pause and let your breathing settle.", "Take a sip of water if you would like one.", "Start the next movement when you feel ready."],
  "bodyweight squats": ["Stand with feet about shoulder-width apart.", "Send hips back and bend knees while keeping your chest comfortable and upright.", "Press through the whole foot to stand; use a chair as a depth guide if helpful."],
  "squats": ["Stand with feet about shoulder-width apart.", "Sit hips back and bend knees in line with your toes.", "Keep heels grounded and stand by pressing through the whole foot."],
  "tempo squats": ["Set feet about shoulder-width apart and brace gently.", "Lower slowly for about three seconds, keeping knees aligned with toes.", "Rise smoothly through the whole foot without locking your knees."],
  "wall push-ups": ["Face a wall and place hands at chest height, a little wider than shoulders.", "Step back until the position feels manageable; keep a straight line from head to hips.", "Bend elbows to bring your chest toward the wall, then press away."],
  "push-ups": ["Place hands slightly wider than shoulders and make a long line from head to heels.", "Brace your middle and lower with elbows angled gently back.", "Press the floor away; use knees or a sturdy raised surface to scale the movement."],
  "knee push-ups": ["Place hands slightly wider than shoulders and keep a straight line from head to knees.", "Bend elbows gently back and lower your chest with control.", "Press the floor away without letting hips sag."],
  "incline push-ups": ["Use a stable wall, desk, or bench and place hands slightly wider than shoulders.", "Step back and keep your body in one line from head to heels.", "Lower your chest toward your hands, then press away with control."],
  "standing knee drives": ["Stand tall with a soft bend in both knees.", "Lift one knee toward hip height while keeping your trunk steady.", "Lower quietly and alternate sides at a comfortable pace."],
  "child’s pose": ["Kneel comfortably and bring your hips toward your heels.", "Reach arms forward or rest them by your sides, whichever is comfortable.", "Breathe slowly; stop or adjust if your knees or hips feel uncomfortable."],
  "reverse lunges": ["Stand tall with feet under hips and hands relaxed.", "Step one foot back and bend both knees only as far as comfortable.", "Push through the front foot to return; alternate sides and keep balance supported if needed."],
  "lunges": ["Stand tall and take a comfortable step forward.", "Bend both knees gently while keeping the front knee pointed with the toes.", "Push through the front foot to return; use a wall for balance if needed."],
  "glute bridges": ["Lie on your back with knees bent and feet flat about hip-width apart.", "Gently brace and press through your feet to lift your hips.", "Pause briefly, then lower with control without arching your back."],
  "single-leg glute bridge": ["Lie on your back with one knee bent and the other leg lifted comfortably.", "Press through the planted foot and lift your hips without twisting.", "Lower slowly; switch legs and use a two-foot bridge if needed."],
  "plank": ["Set forearms or hands beneath your shoulders and extend legs behind you.", "Keep head, shoulders, hips, and heels in one comfortable line.", "Breathe steadily; lower your knees to shorten the hold when needed."],
  "crunches": ["Lie on your back with knees bent and feet grounded.", "Rest hands lightly by your head or across your chest.", "Exhale and lift your shoulders a little; lower slowly without pulling your neck."],
  "mountain climbers": ["Start in a stable high plank with hands below shoulders.", "Bring one knee forward toward your chest while keeping your hips steady.", "Alternate legs slowly first; step rather than hop to reduce impact."],
  "dead bugs": ["Lie on your back with arms up and knees bent above your hips.", "Gently brace so your lower back stays comfortably supported.", "Lower opposite arm and leg only as far as you can control, then alternate."],
  "shoulder press": ["Stand or sit tall with light weights near shoulder height.", "Press upward smoothly while keeping ribs relaxed and wrists stacked.", "Lower to shoulder height with control; stop if shoulders pinch."],
  "arm raises": ["Stand tall with light weights by your sides or use no weight.", "Raise arms out to the sides only to a comfortable height.", "Lower slowly and keep shoulders relaxed away from your ears."],
  "bicep curl": ["Stand tall with light weights and elbows close to your sides.", "Bend elbows to bring hands toward shoulders without swinging.", "Lower slowly until arms are comfortable, keeping wrists neutral."],
  "jumping jacks": ["Stand tall with feet together and arms by your sides.", "Step or hop feet apart as arms rise only as high as comfortable.", "Return softly; use a step-out version to keep the movement low impact."],
  "high knees": ["Stand tall with soft knees and relaxed shoulders.", "Lift one knee at a time to a comfortable height while moving arms naturally.", "Keep steps light; slow down or march if impact feels uncomfortable."],
  "burpees": ["Stand with feet comfortable apart; squat and place hands on a stable surface or floor.", "Step feet back one at a time into a plank, keeping your body controlled.", "Step forward and stand; skip the jump and elevate hands to scale the move."],
  "cat-cow": ["Come to hands and knees with hands under shoulders.", "Inhale and gently lengthen your chest forward without forcing your back.", "Exhale and round your spine softly; move with your breath."],
  "world’s greatest stretch": ["Step into a comfortable lunge with hands supported on a chair or floor.", "Rotate your chest gently toward the front leg without forcing range.", "Return to center, switch sides, and use a shorter stance if needed."],
  "hip flexor stretch": ["Kneel on a padded surface with one foot forward.", "Gently tuck your pelvis and shift forward until you feel a mild stretch.", "Keep your torso tall, breathe, and switch sides; avoid sharp pinching."],
  "thoracic rotations": ["Sit or kneel comfortably with hands resting across your chest.", "Turn your upper back gently to one side while hips stay facing forward.", "Return to center and alternate without forcing the range."],
  "easy forward fold": ["Stand with knees soft and feet comfortably apart.", "Hinge at your hips and let your hands rest on thighs, shins, or a support.", "Breathe easily and rise slowly, keeping the bend in your knees."],
  "calf raises": ["Stand near a wall or chair for balance with feet hip-width apart.", "Rise onto the balls of your feet without rolling your ankles outward.", "Lower slowly; use a smaller range if balance feels uncertain."],
  "tree pose": ["Stand near a wall and shift weight onto one foot.", "Place the other foot at your ankle or calf, never directly on the knee.", "Keep a soft gaze and use wall support; switch sides when ready."],
  "downward dog": ["Start on hands and knees with hands shoulder-width apart.", "Tuck toes and lift hips back, keeping knees bent as needed.", "Press hands gently down and let your head relax between your arms."],
  "warrior pose": ["Stand in a comfortable wide stance and turn one foot outward.", "Bend the front knee only as far as comfortable and keep it tracking over the foot.", "Reach arms out at a relaxed height, breathe, then switch sides."],
  "mountain pose": ["Stand with feet grounded and weight balanced across both feet.", "Lengthen through the crown of your head and relax your shoulders.", "Breathe slowly with knees soft and jaw relaxed."],
  "low lunge": ["Step one foot forward and lower the back knee onto padding if comfortable.", "Keep hands supported and lift your chest gently.", "Shift forward only until you feel a mild stretch, then switch sides."],
  "warrior ii": ["Stand wide, turn one foot out, and reach arms comfortably to the sides.", "Bend the front knee gently in line with the toes while keeping the back leg steady.", "Look over the front hand softly, breathe, and repeat on the other side."],
  "seated twist": ["Sit comfortably with your spine long and both sit bones grounded.", "Turn gently from your ribs, using a hand on your thigh for light support.", "Breathe without forcing the twist, then change sides."],
};

export function instructionsForExercise(name: string): string[] {
  const key = name.trim().toLowerCase().replace(/\s*·.*$/, "").replace(/\s*\d+\s*(sec|seconds|reps?).*$/i, "").trim();
  return movementInstructions[key] ?? [
    `Set up ${key} in a stable, comfortable position.`,
    "Move slowly through a range you can control, keeping your breathing easy.",
    "Pause or choose a gentler variation if you feel pain, dizziness, or unusual discomfort.",
  ];
}

export const quests = [
  {
    id: "move",
    name: "Move your way",
    description: "Complete any workout today.",
    reward: 50,
    coins: 12,
    icon: "✳",
    progress: 0,
  },
  {
    id: "walk",
    name: "Take the long way",
    description: "Take a mindful 10-minute walk.",
    reward: 40,
    coins: 10,
    icon: "↗",
    progress: 0,
  },
  {
    id: "water",
    name: "Refill & reset",
    description: "Log 5 glasses of water.",
    reward: 25,
    coins: 8,
    icon: "◉",
    progress: 0,
  },
  {
    id: "stretch",
    name: "Unwind between classes",
    description: "Finish a mobility or yoga session.",
    reward: 35,
    coins: 10,
    icon: "〰",
    progress: 0,
  },
];
export const poses = [
  {
    name: "Mountain pose",
    time: "1 min",
    level: "Beginner",
    detail:
      "Stand tall with feet grounded. Relax your shoulders and breathe slowly.",
    symbol: "△",
  },
  {
    name: "Low lunge",
    time: "2 min",
    level: "Beginner",
    detail:
      "Step one foot back, soften the back knee, and lift through your chest.",
    symbol: "◜",
  },
  {
    name: "Warrior II",
    time: "2 min",
    level: "Intermediate",
    detail: "Bend the front knee over the ankle. Reach long through both arms.",
    symbol: "↔",
  },
  {
    name: "Seated twist",
    time: "2 min",
    level: "All levels",
    detail: "Sit tall and rotate gently from your ribs. Keep the breath easy.",
    symbol: "⤺",
  },
];
